-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 18:26:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto` ;

-- -----------------------------------------------------
-- Table `Proyecto`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Empresa` (
  `Empresa` VARCHAR(5) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Moneda` (
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  `Clave` VARCHAR(10) NULL,
  PRIMARY KEY (`Moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Proyecto` (
  `Proyecto` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Prov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Prov` (
  `Proveedor` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Gasto` (
  `Clave` VARCHAR(5) NOT NULL,
  `ID` INT NOT NULL,
  `Empresa` VARCHAR(5) NOT NULL,
  `Movimiento` VARCHAR(20) NOT NULL,
  `Consecutivo` VARCHAR(20) NULL,
  `Proveedor` VARCHAR(20) NOT NULL,
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  PRIMARY KEY (`Clave`, `ID`),
  INDEX `IDX_Gasto00` (`Empresa` ASC) VISIBLE,
  INDEX `IDX_Gasto01` (`Moneda` ASC) INVISIBLE,
  INDEX `IDX_Gasto02` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_Gasto00`
    FOREIGN KEY (`Empresa`)
    REFERENCES `Proyecto`.`Empresa` (`Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gasto01`
    FOREIGN KEY (`Moneda`)
    REFERENCES `Proyecto`.`Moneda` (`Moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gasto02`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Proyecto`.`Prov` (`Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Compra` (
  `Clave` VARCHAR(5) NOT NULL,
  `ID` INT NOT NULL,
  `Empresa` VARCHAR(5) NOT NULL,
  `Movimiento` VARCHAR(20) NOT NULL,
  `Consecutivo` VARCHAR(20) NULL,
  `Proveedor` VARCHAR(20) NOT NULL,
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  PRIMARY KEY (`Clave`, `ID`),
  INDEX `IDX_Compra00` (`Empresa` ASC) VISIBLE,
  INDEX `IDX_Compra01` (`Moneda` ASC) VISIBLE,
  INDEX `IDX_Compra02` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_Compra00`
    FOREIGN KEY (`Empresa`)
    REFERENCES `Proyecto`.`Empresa` (`Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Compra01`
    FOREIGN KEY (`Moneda`)
    REFERENCES `Proyecto`.`Moneda` (`Moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Compra02`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Proyecto`.`Prov` (`Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Cxp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Cxp` (
  `Clave` VARCHAR(5) NOT NULL,
  `ID` INT NOT NULL,
  `Empresa` VARCHAR(5) NOT NULL,
  `Movimiento` VARCHAR(20) NOT NULL,
  `Consecutivo` VARCHAR(20) NULL,
  `Proveedor` VARCHAR(20) NOT NULL,
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  PRIMARY KEY (`Clave`, `ID`),
  INDEX `IDX_Cxp01` (`Moneda` ASC) VISIBLE,
  INDEX `IDX_Cxp00` (`Empresa` ASC) VISIBLE,
  INDEX `IDX_Cxp02` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_Cxp00`
    FOREIGN KEY (`Empresa`)
    REFERENCES `Proyecto`.`Empresa` (`Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cxp01`
    FOREIGN KEY (`Moneda`)
    REFERENCES `Proyecto`.`Moneda` (`Moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cxp02`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Proyecto`.`Prov` (`Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Dinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Dinero` (
  `Clave` VARCHAR(5) NOT NULL,
  `ID` INT NOT NULL,
  `Empresa` VARCHAR(5) NOT NULL,
  `Movimiento` VARCHAR(20) NOT NULL,
  `Consecutivo` VARCHAR(20) NULL,
  `Proveedor` VARCHAR(20) NOT NULL,
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  PRIMARY KEY (`Clave`, `ID`),
  INDEX `IDX_Dinero00` (`Empresa` ASC) VISIBLE,
  INDEX `IDX_Dinero01` (`Moneda` ASC) VISIBLE,
  INDEX `IDX_Dinero02` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_Dinero00`
    FOREIGN KEY (`Empresa`)
    REFERENCES `Proyecto`.`Empresa` (`Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Dinero01`
    FOREIGN KEY (`Moneda`)
    REFERENCES `Proyecto`.`Moneda` (`Moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Dinero02`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Proyecto`.`Prov` (`Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Presupuesto` (
  `Clave` VARCHAR(10) NOT NULL,
  `ID` INT NOT NULL,
  `Empresa` VARCHAR(5) NOT NULL,
  `Movimiento` VARCHAR(20) NOT NULL,
  `Consecutivo` VARCHAR(20) NULL,
  `Observaciones` VARCHAR(100) NULL,
  `Referencia` VARCHAR(100) NULL,
  `Proyecto` VARCHAR(50) NOT NULL,
  `Moneda` VARCHAR(10) NOT NULL,
  `TipoCambio` FLOAT NOT NULL,
  `OModulo` VARCHAR(5) NULL,
  `OID` INT NULL,
  `OMov` VARCHAR(20) NULL,
  `OMovID` VARCHAR(20) NULL,
  `Fecha` DATETIME NOT NULL,
  `Ejercicio` INT NOT NULL,
  `Periodo` INT NOT NULL,
  PRIMARY KEY (`Clave`, `ID`),
  INDEX `IDX_Presupuesto00` (`Empresa` ASC) VISIBLE,
  INDEX `IDX_Presupuesto01` (`Moneda` ASC) VISIBLE,
  INDEX `IDX_Presupuesto02` (`Proyecto` ASC) VISIBLE,
  INDEX `IDX_Presupuesto03` (`OID` ASC, `OModulo` ASC) VISIBLE,
  CONSTRAINT `FK_Presupuesto00`
    FOREIGN KEY (`Empresa`)
    REFERENCES `Proyecto`.`Empresa` (`Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto01`
    FOREIGN KEY (`Moneda`)
    REFERENCES `Proyecto`.`Moneda` (`Moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto02`
    FOREIGN KEY (`Proyecto`)
    REFERENCES `Proyecto`.`Proyecto` (`Proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto03`
    FOREIGN KEY (`OID` , `OModulo`)
    REFERENCES `Proyecto`.`Gasto` (`ID` , `Clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto04`
    FOREIGN KEY (`OID` , `OModulo`)
    REFERENCES `Proyecto`.`Compra` (`ID` , `Clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto05`
    FOREIGN KEY (`OID` , `OModulo`)
    REFERENCES `Proyecto`.`Cxp` (`ID` , `Clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Presupuesto06`
    FOREIGN KEY (`OID` , `OModulo`)
    REFERENCES `Proyecto`.`Dinero` (`ID` , `Clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`ClavePresupuestal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`ClavePresupuestal` (
  `ClavePresupuestal` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ClavePresupuestal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`PresupuestoD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`PresupuestoD` (
  `Clave` VARCHAR(5) NOT NULL,
  `ID` INT NOT NULL,
  `Renglon` FLOAT NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `ClavePresupuestal` VARCHAR(50) NOT NULL,
  `Importe` FLOAT NULL,
  `Presupuesto` FLOAT NULL,
  `Fase0` FLOAT NULL,
  `Fase1` FLOAT NULL,
  `Fase2` FLOAT NULL,
  `Fase3` FLOAT NULL,
  `Fase4` FLOAT NULL,
  `Disponible` FLOAT GENERATED ALWAYS AS (Presupuesto-Fase0-Fase1-Fase2-Fase3-Fase4) VIRTUAL,
  PRIMARY KEY (`Clave`, `ID`, `Renglon`),
  INDEX `IDX_PresupuestoD01` (`ClavePresupuestal` ASC) VISIBLE,
  CONSTRAINT `FK_PresupuestoD00`
    FOREIGN KEY (`Clave` , `ID`)
    REFERENCES `Proyecto`.`Presupuesto` (`Clave` , `ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PresupuestoD01`
    FOREIGN KEY (`ClavePresupuestal`)
    REFERENCES `Proyecto`.`ClavePresupuestal` (`ClavePresupuestal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
